# This file is auto-generated by build.ps1 at build time.
# When running from source it holds placeholder values.
VERSION    = "1.0"
BUILD_DATE = None   # replaced with "YYYY-MM-DD HH:MM:SS" by build.ps1
